---
title: "Getting started with RHEL Kickstart files"
tags:
  - RHEL
last_modified_at: '2022-05-03'
---
# RHEL-Kickstart
RedHat and its derivatives can utilize special configuration files called "Kickstart files" to make installation automated and repeatable. I wanted to explore this for my [RHEL Migration]() project where I am moving from CentOS 7 to RHEL 8.

## Obtaining a basic configuration
The simplest way to get a basic Kickstart file is to install your distro like you normally would then copy the `anaconda-ks.cfg` file that is generated by the installer (called Anaconda) and left in `/root` on your new system. This file contains the parameters that you chose during your graphical setup process. It holds all settings including:

* Package selection
* Keyboard layout and language selection
* Network configurations
  * Hostname
  * Static/DHCP settings
* Disk layouts
* Timezone
* Root password and optional user configurations
* Password policies

## Using your Kickstart file for an unattended install

## Changes you can make to the Kickstart file
### Package management

### Network configuration

### Register with RedHat automatically
